// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Order struct {
	ID         int32
	UserID     int32
	ProductID  int32
	Quantity   int
	TotalPrice float64
	CreatedAt  sql.NullTime
}

type Product struct {
	ID    int32
	Name  string
	Price float64
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
