// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Product struct {
	ID    int32
	Name  string
	Price string
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
