version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: shop_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Ваше Go-приложение
  app:
    build: .
    container_name: go_app
    environment:
      DB_HOST: db
      DB_USER: shop_user
      DB_PASSWORD: 12345
      DB_NAME: shop_db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
